version: "3.8"
services:
  pokemon-frontend:
    container_name: pokemon-names_pokemon-frontend
    image: ${AUTHOR}/pokemon-frontend
    build: ./service_1
    deploy:
        replicas: 5
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  pokemon-backend:
    container_name: pokemon-names_pokemon-backend
    image: ${AUTHOR}/pokemon-backend
    build: ./service_2
    deploy:
        replicas: 5
  pokemon-backend3:
    container_name: pokemon-psa_pokemon-backend3
    image: ${AUTHOR}/pokemon-backend3
    build: ./service_3
    deploy:
        replicas: 5
  pokemon-backend4:
    container_name: pokemon-eva_pokemon-backend4
    image: ${AUTHOR}/pokemon-backend4
    build: ./service_4
    deploy:
        replicas: 5
